server:
  port: 8081

spring:
  application:
    name: skyways-user-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URI:localhost:8888}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/user_db
    username: ${DB_USER:skyways}
    password: ${DB_PASS:skyways_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

gcp:
  project-id: ${GCP_PROJECT_ID:skyways-airlines-prod}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  config: classpath:log4j2.xml
