server:
  port: 8085

spring:
  application:
    name: skyways-notification-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URI:localhost:8888}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.skyways.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

skyways:
  notification:
    from-email: ${SENDGRID_FROM_EMAIL:bookings@skyways.com}

gcp:
  project-id: ${GCP_PROJECT_ID:skyways-airlines-prod}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  config: classpath:log4j2.xml
